{% set version = '7.3-11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatial
  version: {{ version|replace("-", "_") }}

source:
  fn: spatial_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/spatial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatial/spatial_{{ version }}.tar.gz
  sha256: 624448d2ac22e1798097d09fc5dc4605908a33f490b8ec971fc6ea318a445c11

build:
  merge_build_host: True  # [win]
  number: 1002

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('spatial')"           # [not win]
    - "\"%R%\" -e \"library('spatial')\""  # [win]

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Functions for kriging and point pattern analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - dbast
