# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mI4D9wFEyP9KSZOEceoxFuB7+gde5S6r/d1rUrcBt2i7Wqb9kw40kA+0KtFPysAMoWDmVOUkdhtk7tzhnUazw7AD7e8kuJP8WeMS5Kv/w+Ckc246j+eeV+3EWnq/EpiRPyYgolhKUSPV6uh3AMu6Tylhp1tJB1++Nyugh8q3tkjbBBlkHu+bB8t4jmbTchzFX+gH+ZXjM3JWnrADr1g9P6dQ/DLkc0r/I5s7204Ho0YK+nEzeoBO4JySAGchF2JGzyQQFHOjbDiaEeyopsvKGXoNhOPz6OgY0iVZq5dqFZpK2RjFZXQ98ey4tWxC58zEra2SHbpA17hmaMy0MsM7ctf/scbmfeNz3UmdeLU/afdw1oZV7U2HioAS+uYj/ee3gP6Yi8/02dBSMG4Gq4PUrW9hJuMuhY5MpahSgSChR6z3R/jkAgVhx9O68Annubg/Wv46YmquP6jsa2fC5QlhHgSwyienzmwDevuYrhrLJ7bq9b4A76/d8/T4JnKDHXD+PsNZI7byzwfmMYgyQ/cdBqfGKd1f9EbNoExy/iTQGLCLZF22XJi0liSqPc4Dbt2MBBor2jevOIycENdfh2vPaTgECws9DMMuHCMGRtwXKKKcQ2Da+8ZnyAbIndDM/acxIA3oQi5Z/TxxaJzRpQ5nl+ko81mXAsD32q4d4tCCHvU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
