travis:
  secure:
    BINSTAR_TOKEN: mI4D9wFEyP9KSZOEceoxFuB7+gde5S6r/d1rUrcBt2i7Wqb9kw40kA+0KtFPysAMoWDmVOUkdhtk7tzhnUazw7AD7e8kuJP8WeMS5Kv/w+Ckc246j+eeV+3EWnq/EpiRPyYgolhKUSPV6uh3AMu6Tylhp1tJB1++Nyugh8q3tkjbBBlkHu+bB8t4jmbTchzFX+gH+ZXjM3JWnrADr1g9P6dQ/DLkc0r/I5s7204Ho0YK+nEzeoBO4JySAGchF2JGzyQQFHOjbDiaEeyopsvKGXoNhOPz6OgY0iVZq5dqFZpK2RjFZXQ98ey4tWxC58zEra2SHbpA17hmaMy0MsM7ctf/scbmfeNz3UmdeLU/afdw1oZV7U2HioAS+uYj/ee3gP6Yi8/02dBSMG4Gq4PUrW9hJuMuhY5MpahSgSChR6z3R/jkAgVhx9O68Annubg/Wv46YmquP6jsa2fC5QlhHgSwyienzmwDevuYrhrLJ7bq9b4A76/d8/T4JnKDHXD+PsNZI7byzwfmMYgyQ/cdBqfGKd1f9EbNoExy/iTQGLCLZF22XJi0liSqPc4Dbt2MBBor2jevOIycENdfh2vPaTgECws9DMMuHCMGRtwXKKKcQ2Da+8ZnyAbIndDM/acxIA3oQi5Z/TxxaJzRpQ5nl+ko81mXAsD32q4d4tCCHvU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
